name: app_turismo
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  get_it: ^7.2.0
  equatable: ^2.0.5
  image_picker: ^1.0.2
  google_fonts: ^3.0.0
  firebase_database: ^10.0.7
  cloud_firestore: ^4.3.0
  firebase_auth: ^4.2.3
  firebase_core: ^2.4.0
  firebase_storage: ^11.0.9
  geolocator: ^9.0.2
  geocoding: ^2.0.5
  geolocator_web: ^2.1.6
  font_awesome_flutter: ^10.4.0
  google_maps_flutter: ^2.4.0
  auto_size_text: ^3.0.0
  carousel_slider: ^4.2.1
  email_validator: ^2.1.17
  multi_select_flutter: ^4.1.3
  bootstrap_icons: ^1.10.5+2
  image_cropper: ^4.0.1
  json_serializable: ^6.7.1
  http: ^0.13.6
  dotted_border: ^2.0.0+3
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6

flutter_icons:
  android: true
  ios: true
  image_path: "assets/Logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/img/

  fonts:
    - family: Ubuntu
      fonts:
        - asset: fonts/Ubuntu-Bold.ttf
        - asset: fonts/Ubuntu-Italic.ttf
        - asset: fonts/Ubuntu-Light.ttf
        - asset: fonts/Ubuntu-Medium.ttf
        - asset: fonts/Ubuntu-Regular.ttf
